# Generated by Django 4.2.16 on 2024-09-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='anggota',
        ),
    ]
