# Generated by Django 4.2.16 on 2024-09-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_member_anggota'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='asal',
            field=models.CharField(default='Tidak diketahui', max_length=255),
        ),
    ]
