# Generated by Django 4.2.16 on 2024-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_anggota_asal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='asal',
            field=models.CharField(max_length=255),
        ),
    ]
