# Generated by Django 4.2.16 on 2024-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_anggota_asal'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
