# Generated by Django 4.2.16 on 2024-09-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_anggota_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='slug',
        ),
    ]
